---
- name: Install dehydrated
  become: true
  ansible.builtin.apt:
    name:
      - dehydrated
    state: latest

- name: Install dehydrated-apache2
  become: true
  ansible.builtin.apt:
    name:
      - apache2
      - dehydrated-apache2
    state: latest
  when:
    - dehydrated.challenge_type == 'http-01'
    - dehydrated.use_apache2

- name: Install bind9-dnsutils
  become: true
  ansible.builtin.package:
    name:
      - bind9-dnsutils
    state: latest
  when: dehydrated.challenge_type == 'dns-01'

- name: Create per-domain configuration directory
  become: true
  ansible.builtin.file:
    path: /etc/dehydrated/domains.d
    state: directory
    mode: "0640"
    owner: root
    group: root
  when: dehydrated.per_domain_config

- name: Configure dehydrated account
  become: true
  ansible.builtin.template:
    src: account.sh.j2
    dest: /etc/dehydrated/conf.d/account.sh
    mode: "0600"
    owner: root
    group: root
  notify:
    - Update account info

- name: Configure dehydrated options
  become: true
  ansible.builtin.template:
    src: options.sh.j2
    dest: /etc/dehydrated/conf.d/options.sh
    mode: "0640"
    owner: root
    group: root

- name: Configure dehydrated domains
  become: true
  ansible.builtin.template:
    src: domains.txt.j2
    dest: /etc/dehydrated/domains.txt
    mode: "0640"
    owner: root
    group: root
  notify:
    - Renew certificates

- name: Register account
  become: true
  ansible.builtin.command:
    cmd: dehydrated --register --accept-terms
    creates: /var/lib/dehydrated/accounts/*/account_id.json

- name: Create TSIG key
  become: true
  ansible.builtin.template:
    src: nsupdate.key.j2
    dest: /etc/dehydrated/nsupdate.key
    mode: "0600"
    owner: root
    group: root
  when: dehydrated.challenge_type == 'dns-01'

- name: Install dehydrated systemd service
  become: true
  ansible.builtin.copy:
    src: dehydrated.service
    dest: /etc/systemd/system/dehydrated.service
    mode: "0644"
    owner: root
    group: root
  notify:
    - Reload systemd

- name: Install dehydrated systemd timer
  become: true
  ansible.builtin.copy:
    src: dehydrated.timer
    dest: /etc/systemd/system/dehydrated.timer
    mode: "0644"
    owner: root
    group: root
  notify:
    - Reload systemd

- name: Enable dehydrated systemd timer
  become: true
  ansible.builtin.systemd:
    name: dehydrated.timer
    state: started
    enabled: true
    daemon_reload: true
...
